apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: okular-us-tls
spec:
  secretName: okular-us
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: okular.us
  dnsNames:
    - okular.us
    - www.okular.us