apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    # UPDATE THIS LINE ABOVE
spec:
  tls: 
    - hosts:
        - okular.us
        - www.okular.us
      secretName: okular-us-tls
  rules:
    - host: okular.us
      http:
        paths:
          - path: /?(.*)
            # UPDATE THIS LINE ABOVE
            pathType: Prefix
            backend:
              service:
                name: client-cluster-ip-service
                port: 
                  number: 3000
          - path: /api/?(.*)
            # UPDATE THIS LINE ABOVE
            pathType: Prefix
            backend:
              service:
                name: server-cluster-ip-service
                port: 
                  number: 5000
    - host: www.okular.us
      http:
        paths:
          - path: /?(.*)
            # UPDATE THIS LINE ABOVE
            pathType: Prefix
            backend:
              service:
                name: client-cluster-ip-service
                port: 
                  number: 3000
          - path: /api/?(.*)
            # UPDATE THIS LINE ABOVE
            pathType: Prefix
            backend:
              service:
                name: server-cluster-ip-service
                port: 
                  number: 5000