apiVersion: apps/v1
kind: Deployment
metadata:
  name: jserv-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: jserv
  template:
    metadata:
      labels:
        component: jserv
    spec:
      containers:
        - name: jserv
          image: ocular2020/jserv
          livenessProbe:
            httpGet:
              port: 9080
              path: /
          readinessProbe:
            httpGet:
              port: 9080
              path: /jserv/resources/health
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThresholdId: 2
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "curl www.okular.us/japi/jserv/resources/health", -XDELETE && sleep 25"]

          ports:
            - containerPort: 9080
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword 
                  key: PGPASSWORD
          


